---
- name: Install packages
  yum:
    name: "{{ item }}"
    state: installed
  with_items:
    - git
  become: yes
  become_user: root

- name: Ensure 'asterisk' group exists
  group:
    name: asterisk
    state: present
  become: yes
  become_user: root

- user:
    name: git
    groups: asterisk
    append: yes
    createhome: yes
    state: present
  become: yes
  become_user: root

- name: Pull Dial Plans
  git:
    repo: git@github.com:{{ git_repo.name }}.git
    dest: "{{ git_repo.checkout_dir }}"
    update: yes
    force: yes
    accept_hostkey: yes
  become: yes
  become_user: git

- name: Checkout tag
  shell: git checkout {{ git_tag }}
  args:
    chdir: "{{ git_repo.checkout_dir }}"
  when:  "git_tag is defined and git_tag != ''"
  become: yes
  become_user: git

- name: Set owner on /etc/asterisk
  file:
    path: /etc/asterisk
    state: directory
    recurse: true
    owner: git
    group: asterisk
    mode: 0775

# Directories need +x, files don't
- name: Set Permissions on /etc/asterisk
  shell: find /etc/asterisk -type d -print0 | xargs -0 chmod 0775
  register: chmod_result
  changed_when: "chmod_result.stdout != \"\""

- name: Set permissions on *.conf files
  shell: find /etc/asterisk -type f -print0 | xargs -0 chmod 0664
